"""topic status

Revision ID: 58efce143903
Revises: 
Create Date: 2018-08-27 20:48:38.122771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58efce143903'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("polls") as batch_op:
        batch_op.drop_column('status')
    op.add_column('topics', sa.Column('status', sa.Boolean(), default=1))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'status')
    # ### end Alembic commands ###
